name: Assembly

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run assembly
      run: sbt assembly
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: hydrogenchairs
        path: target/build/HydrogenChairs-*.jar
